# Generated by Django 3.1.6 on 2021-04-26 15:03

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 15, 3, 36, 331961, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 15, 3, 36, 330962, tzinfo=utc)),
        ),
    ]
