# Generated by Django 3.1.6 on 2021-04-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210426_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageUrl',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
